# For more information: https://laravel.com/docs/sail
version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: "php artisan serve --host=0.0.0.0"
    ports:
      - 8000:8000
    depends_on:
      - mysql_db
      - redis

  kitchen:
    build:
      context: .
      dockerfile: Dockerfile
    command: "php artisan queue:work"
    ports:
      - 3000:3000
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:5.7.22
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: lunch
      MYSQL_USER: lunch
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql_db
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

  redis:
    image: redis:4-alpine
 

 